name: Swift CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Select Xcode Version
      run: |
        sudo xcode-select -s /Applications/Xcode_15.2.app
        xcodebuild -version

    - name: Show Directory Structure
      run: |
        ls -la
        xcodebuild -list -project PokeVerse.xcodeproj

    - name: Build Project
      run: |
        xcodebuild \
          -project PokeVerse.xcodeproj \
          -scheme "PokeVerse" \
          -destination "platform=iOS Simulator,name=iPhone 14" \
          clean build

    - name: Run Unit Tests
      run: |
        xcodebuild \
          -project PokeVerse.xcodeproj \
          -scheme "PokeVerse" \
          -destination "platform=iOS Simulator,name=iPhone 14" \
          test
