name: Swift CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Convert Project to XML
      run: |
        plutil -convert xml1 PokeVerse.xcodeproj/project.pbxproj

    - name: Select Xcode 15.2
      run: |
        sudo xcode-select -s /Applications/Xcode_15.2.app
        xcodebuild -version

    - name: Debug Directory Structure
      run: |
        ls -la
        xcodebuild -list -project PokeVerse.xcodeproj

    - name: Build
      run: |
        xcodebuild \
          -project PokeVerse.xcodeproj \
          -scheme "PokeVerse" \
          -destination "platform=iOS Simulator,OS=latest" \
          clean build

    - name: Run Tests
      run: |
        xcodebuild \
          -project PokeVerse.xcodeproj \
          -scheme "PokeVerse" \
          -destination "platform=iOS Simulator,OS=latest" \
          test

