name: Build and Show Coverage

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  build-and-coverage:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.0.app

      - name: Run tests with coverage
        run: |
          xcodebuild \
            -project PokeVerse.xcodeproj \
            -scheme PokeVerse \
            -destination 'platform=iOS Simulator,name=iPhone 14' \
            -enableCodeCoverage YES \
            test

      - name: Install xcov
        run: sudo gem install xcov

      - name: Show coverage report
        run: |
          mkdir -p coverage
          xcov \
            --project PokeVerse.xcodeproj \
            --scheme PokeVerse \
            --output_directory coverage \
            --only_project_targets \
            --disable_xcpretty
